export const GET_SERVICE_REQUEST_WEEKS = "GET_SERVICE_REQUEST_WEEKS";
export const GET_SERVICE_REQUEST_DEFAULT_WEEK =
  "GET_SERVICE_REQUEST_DEFAULT_WEEK";
export const SET_SERVICE_REQUEST_SELECTED_WEEK =
  "SET_SERVICE_REQUEST_SELECTED_WEEK";
export const GET_SERVICE_REQUEST_SCHEDULE_REPORT_GROUP_BY_COMPANY =
  "GET_SERVICE_REQUEST_SCHEDULE_REPORT_GROUP_BY_COMPANY";
